language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="netchannel:. mirage-net-xen:. shared-memory-ring"
  - PACKAGE="mirage-net-xen"
  matrix:
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03.0"
  - DISTRO="alpine-3.5" OCAML_VERSION="4.04.0"
